params:
  seed: 77

  # environment wrapper clipping
  env:
    # added to the wrapper
    clip_observations: 50.0
    # can make custom wrapper?
    clip_actions: 1.0

  algo:
    name: a2c_continuous

  model:
    # name: continuous_a2c_logstd
    name: continuous_a2c_tanh # tanh squashed gaussian

  # doesn't have this fine grained control but made it close
  network:
    name: actor_critic_encoder
    separate: False
    space:
      continuous:
        mu_activation: None
        sigma_activation: None

        mu_init:
          # name: default
          name: const_initializer
          val: 0
        sigma_init:
          name: const_initializer
          val: 0
        fixed_sigma: True
    
    encoder:
      network_type: mlp
      units: [256, 128, 8]
      activation: elu
      d2rl: False

      initializer:
        # name: default
        # name: kaiming_normal
        name: orthogonal
      regularizer:
        name: None

    mlp:
      units: [512, 256, 128]
      activation: elu
      d2rl: False

      initializer:
        # name: default
        # name: kaiming_normal
        name: orthogonal
      regularizer:
        name: None

  load_checkpoint: False # flag which sets whether to load the checkpoint
  load_path: '' # path to the checkpoint to load

  config:
    name: manager_ppo_mlp_encoder_rl_games_stepping_stone_mlp
    env_name: rlgpu
    device: 'cuda:0'
    device_name: 'cuda:0'
    multi_gpu: False
    ppo: True
    mixed_precision: True
    normalize_input: True
    normalize_value: True
    num_actors: -1  # configured from the script (based on num_envs)
    reward_shaper:
      scale_value: 1.0
    normalize_advantage: True
    gamma: 0.99
    tau : 0.95
    learning_rate: 1e-4
    lr_schedule: adaptive
    kl_threshold: 0.01
    score_to_win: 20000
    max_epochs: 40000
    save_best_after: 500
    save_frequency: 500
    grad_norm: 1.0
    entropy_coef: 0.0
    truncate_grads: True
    e_clip: 0.2
    horizon_length: 24
    minibatch_size: 144 # num_envs*horizon/num_mini_batch=24*24/4
    mini_epochs: 5
    critic_coef: 0.5
    clip_value: false
    seq_length: 4
    bound_loss_type: regularisation
    # bound_loss_type: bound
    bounds_loss_coef: 0.005
  
  log:
    logger: wandb
    wandb_project_name: rl_mpc_manager
    wandb_entity: jnskkmr
    name: manager_ppo_mlp_encoder_rl_games_stepping_stone_mlp